name: example
description: A new Flutter project.

publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adwaita: "0.5.1"
  desktop_multi_window: ">=0.0.1 <1.0.0"
  flutter:
    sdk: flutter
  libadwaita:
    path: ../
  libadwaita_bitsdojo:
    path: ../../plugins/libadwaita_bitsdojo

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png