name: example
description: A new Flutter project.

publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adwaita: "0.5.1"
  desktop_multi_window: ">=0.0.1 <1.0.0"
  flutter:
    sdk: flutter
  libadwaita:
    path: ../
  libadwaita_bitsdojo: ^0.5.3

dependency_overrides:
  bitsdojo_window_linux:
    git:
      url: https://github.com/prateekmedia/bitsdojo_window.git
      path: bitsdojo_window_linux
  bitsdojo_window_macos:
    git:
      url: https://github.com/prateekmedia/bitsdojo_window.git
      path: bitsdojo_window_macos
  bitsdojo_window_windows:
    git:
      url: https://github.com/prateekmedia/bitsdojo_window.git
      path: bitsdojo_window_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png