name: gtk
description: Implements GTK Widgets, themes and titlebar buttons in Flutter. Based on the GNOME HIG
version: 1.0.0-rc.1
homepage: https://github.com/prateekmedia/gtk-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  popover: ">=0.2.6+2 <1.0.0"

dev_dependencies:
  flutter_lints: ">=1.0.0 <2.0.0"

flutter:
