name: libadwaita
description: Libadwaita's widgets for Flutter. Following Gnome HIG and available on all platforms.
version: 1.0.0
homepage: https://github.com/gtk-flutter/libadwaita

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dbus: ">=0.7.1 <1.0.0"
  flutter:
    sdk: flutter
  flutter_svg: ">=1.0.3 < 2.0.0"
  gsettings: ">=0.2.5 <1.0.0"
  package_info_plus: ">=1.3.0 < 2.0.0"
  popover_gtk: ">=0.2.6+3 < 1.0.0"
  url_launcher: ">=6.0.18 < 7.0.0"

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/icons/
