name: libadwaita
description: Unofficial implementation of Libadwaita widgets and themes in Flutter.
version: 1.0.0-rc.1
homepage: https://github.com/gtk-flutter/libadwaita

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ">=0.6.6 <1.0.0"
  gsettings: ">=0.2.1 <1.0.0"

dev_dependencies:
  flutter_lints: ">=1.0.0 <2.0.0"

flutter:
