name: gtk
description: Implements GTK Widgets, themes and titlebar buttons in Flutter. Based on the GNOME HIG
version: 0.1.0
homepage: https://github.com/prateekmedia/gtk_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  adwaita_icons:
  bitsdojo_window:
  popover:
  window_decorations:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: