name: gtk
description: Implements GTK Widgets, themes and titlebar buttons in Flutter. Based on the GNOME HIG
version: 0.8.5
homepage: https://github.com/prateekmedia/gtk-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  from_css_color: ">=2.0.0 <3.0.0"
  gsettings: ">=0.1.2+1 <1.0.0"
  popover: ">=0.2.6 <1.0.0"
  window_decorations: ">=0.3.0 <1.0.0"
  xdg_directories: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <2.0.0"

flutter:
